[build]
  command = "npm install && npm --prefix client install && npm --prefix client run build"
  publish = "client/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."transform"]
  timeout = 26
